# Neural Net Structure

- 3 batches of 4 inputs
- Layer 1: 5 Neurons, 4 weights each -> a weight for each input
- Layer 2: 2 Neurons, 5 weights each -> a weight for each input, which comes from Layer 1 Neuron Outputs
- Output: 2 values for each of the 3 batches -> a value for each of layer 2's neurons, for each batch

How does this work?
- Forward Pass does dot product of inputs and weights (and adds bias).
- If multiple rows of inputs, dot product maps into those new rows.
- - I.e., just a matrix with 1 row instead of 3
- - Matrix with 1 row will do dot product of each element against each element of other's columns
- - Matrix with 3 rows will do dot product of each element of each row against each element of other's columns

In [27]:
import numpy as np
np.random.seed(0)

class Layer:
    def __init__(self, num_inputs, num_neurons):
        self.weights = 0.10 * np.random.randn(num_inputs, num_neurons)
        print("weights:", self.weights)
        self.biases = np.zeros((1, num_neurons))
        self.num_outputs = num_neurons

    def forward_pass(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        return self.output

In [28]:
# 3 batches of 4 inputs
X = [
    [1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]
]

print(len(X))

3


In [29]:
layer1 = Layer(num_inputs=len(X[0]), num_neurons=5)
# Each neuron (5 columns) has 4 weights for each set/"batch" of inputs

weights: [[ 0.17640523  0.04001572  0.0978738   0.22408932  0.1867558 ]
 [-0.09772779  0.09500884 -0.01513572 -0.01032189  0.04105985]
 [ 0.01440436  0.14542735  0.07610377  0.0121675   0.04438632]
 [ 0.03336743  0.14940791 -0.02051583  0.03130677 -0.08540957]]


In [30]:
layer2 = Layer(num_inputs=layer1.num_outputs, num_neurons=2)
# Each neuron (2 columns) has 5 weights (5 rows to hold each input weight)

weights: [[-0.25529898  0.06536186]
 [ 0.08644362 -0.0742165 ]
 [ 0.22697546 -0.14543657]
 [ 0.00457585 -0.01871839]
 [ 0.15327792  0.14693588]]


In [31]:
l1Out = layer1.forward_pass(X)
l2Out = layer2.forward_pass(l1Out)

print(l2Out)
# if X is X = [
#     [1,2,3,2.5],
# ]
# l2Out: [[ 0.148296   -0.08397602]]    -> outputs of the only input

# if X is [
#     [1,2,3,2.5],
#     [2.0,5.0,-1.0,2.0],
#     [-1.5,2.7,3.3,-0.8]
# ]
# l2Out: 
#   [[ 0.148296   -0.08397602]          -> same as the singular X output
#   [ 0.14100315 -0.01340469]           -> next batch
#   [ 0.20124979 -0.07290616]]          -> next batch

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
